# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{formhelper}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["shyamkkhadka"]
  s.date = %q{2010-09-16}
  s.description = %q{This is an API for interacting with simple HTML form.}
  s.email = %q{shyamkkhadka@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "formhelper.gemspec",
     "init.rb",
     "lib/formhelper.rb",
     "lib/formhelper/boolean.rb",
     "lib/formhelper/currency.rb",
     "lib/formhelper/date_answer.rb",
     "lib/formhelper/descriptive_content.rb",
     "lib/formhelper/email.rb",
     "lib/formhelper/field.rb",
     "lib/formhelper/form.rb",
     "lib/formhelper/image_data.rb",
     "lib/formhelper/long_answer.rb",
     "lib/formhelper/multiple_choice.rb",
     "lib/formhelper/number.rb",
     "lib/formhelper/rating.rb",
     "lib/formhelper/short_answer.rb",
     "lib/formhelper/text_data.rb",
     "lib/formhelper/time_answer.rb",
     "lib/formhelper/url.rb",
     "lib/formhelper/utils.rb",
     "rdoc/classes/Array.html",
     "rdoc/classes/FormHelper.html",
     "rdoc/classes/FormHelper/Boolean.html",
     "rdoc/classes/FormHelper/Currency.html",
     "rdoc/classes/FormHelper/DateAnswer.html",
     "rdoc/classes/FormHelper/DescriptiveContent.html",
     "rdoc/classes/FormHelper/DuplicateIDException.html",
     "rdoc/classes/FormHelper/Email.html",
     "rdoc/classes/FormHelper/Field.html",
     "rdoc/classes/FormHelper/Form.html",
     "rdoc/classes/FormHelper/ImageData.html",
     "rdoc/classes/FormHelper/LongAnswer.html",
     "rdoc/classes/FormHelper/MultipleChoice.html",
     "rdoc/classes/FormHelper/Number.html",
     "rdoc/classes/FormHelper/ParameterExpectedException.html",
     "rdoc/classes/FormHelper/Rating.html",
     "rdoc/classes/FormHelper/ShortAnswer.html",
     "rdoc/classes/FormHelper/TextData.html",
     "rdoc/classes/FormHelper/TimeAnswer.html",
     "rdoc/classes/FormHelper/Url.html",
     "rdoc/created.rid",
     "rdoc/files/README_rdoc.html",
     "rdoc/files/lib/formhelper/boolean_rb.html",
     "rdoc/files/lib/formhelper/currency_rb.html",
     "rdoc/files/lib/formhelper/date_answer_rb.html",
     "rdoc/files/lib/formhelper/descriptive_content_rb.html",
     "rdoc/files/lib/formhelper/email_rb.html",
     "rdoc/files/lib/formhelper/field_rb.html",
     "rdoc/files/lib/formhelper/form_rb.html",
     "rdoc/files/lib/formhelper/image_data_rb.html",
     "rdoc/files/lib/formhelper/long_answer_rb.html",
     "rdoc/files/lib/formhelper/multiple_choice_rb.html",
     "rdoc/files/lib/formhelper/number_rb.html",
     "rdoc/files/lib/formhelper/rating_rb.html",
     "rdoc/files/lib/formhelper/short_answer_rb.html",
     "rdoc/files/lib/formhelper/text_data_rb.html",
     "rdoc/files/lib/formhelper/time_answer_rb.html",
     "rdoc/files/lib/formhelper/url_rb.html",
     "rdoc/files/lib/formhelper/utils_rb.html",
     "rdoc/files/lib/formhelper_rb.html",
     "rdoc/fr_class_index.html",
     "rdoc/fr_file_index.html",
     "rdoc/fr_method_index.html",
     "rdoc/index.html",
     "rdoc/rdoc-style.css",
     "test/boolean_test.rb",
     "test/currency_test.rb",
     "test/date_answer_test.rb",
     "test/descriptive_content_test.rb",
     "test/field_test.rb",
     "test/form_test.rb",
     "test/image_data_test.rb",
     "test/long_answer_test.rb",
     "test/multiple_choice_test.rb",
     "test/number_test.rb",
     "test/rating_test.rb",
     "test/short_answer_test.rb",
     "test/test_helper.rb",
     "test/text_data_test.rb",
     "test/time_answer_test.rb",
     "test/url_test.rb"
  ]
  s.homepage = %q{http://github.com/shyamkkhadka/formhelper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{This is an API for interacting with simple HTML form.}
  s.test_files = [
    "test/boolean_test.rb",
     "test/currency_test.rb",
     "test/date_answer_test.rb",
     "test/descriptive_content_test.rb",
     "test/field_test.rb",
     "test/form_test.rb",
     "test/image_data_test.rb",
     "test/long_answer_test.rb",
     "test/multiple_choice_test.rb",
     "test/number_test.rb",
     "test/rating_test.rb",
     "test/short_answer_test.rb",
     "test/test_helper.rb",
     "test/text_data_test.rb",
     "test/time_answer_test.rb",
     "test/url_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<json_pure>, ["~> 1.4.3"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.3"])
    else
      s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
      s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
    end
  else
    s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
    s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
  end
end
