# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{formhelper}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["shyamkkhadka"]
  s.date = %q{2010-09-24}
  s.description = %q{This is a library to create different form field elements, allows form object to parse into different formats (YAML, JSON, XML)
    }
  s.email = %q{shyamkkhadka@gmail.com}
  s.extra_rdoc_files = [
    "README",
     "README.rdoc"
  ]
  s.files = [
    "README"
  ]
  s.homepage = %q{http://github.com/shyamkkhadka/formhelper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{This is a library to create different form field elements, allows form object to parse into different formats (YAML, JSON, XML)}
  s.test_files = [
    "test/boolean_test.rb",
     "test/currency_test.rb",
     "test/date_answer_test.rb",
     "test/descriptive_content_test.rb",
     "test/field_test.rb",
     "test/form_test.rb",
     "test/image_data_test.rb",
     "test/init.rb",
     "test/lib/factoryform/boolean.rb",
     "test/lib/factoryform/currency.rb",
     "test/lib/factoryform/date_answer.rb",
     "test/lib/factoryform/descriptive_content.rb",
     "test/lib/factoryform/email.rb",
     "test/lib/factoryform/field.rb",
     "test/lib/factoryform/form.rb",
     "test/lib/factoryform/image_data.rb",
     "test/lib/factoryform/long_answer.rb",
     "test/lib/factoryform/multiple_choice.rb",
     "test/lib/factoryform/number.rb",
     "test/lib/factoryform/rating.rb",
     "test/lib/factoryform/short_answer.rb",
     "test/lib/factoryform/text_data.rb",
     "test/lib/factoryform/time_answer.rb",
     "test/lib/factoryform/url.rb",
     "test/lib/factoryform/utils.rb",
     "test/lib/factoryform.rb",
     "test/long_answer_test.rb",
     "test/multiple_choice_test.rb",
     "test/number_test.rb",
     "test/rating_test.rb",
     "test/short_answer_test.rb",
     "test/test_helper.rb",
     "test/text_data_test.rb",
     "test/time_answer_test.rb",
     "test/url_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<json_pure>, ["~> 1.4.3"])
      s.add_runtime_dependency(%q<json_pure>, ["~> 1.4.3"])
    else
      s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
      s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
    end
  else
    s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
    s.add_dependency(%q<json_pure>, ["~> 1.4.3"])
  end
end
